version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - ./rabbitmq-definitions.json:/etc/rabbitmq/definitions.json
    command: >
      sh -c "rabbitmq-server &
             sleep 8 &&
             rabbitmqctl import_definitions /etc/rabbitmq/definitions.json &&
             tail -f /dev/null"

  api:
    build: ./api
    container_name: notifications-api
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq

  worker:
    build: ./worker
    container_name: notifications-worker
    depends_on:
      - rabbitmq

  dlq-worker:
    build: ./dlq-worker
    container_name: notifications-dlq-worker
    depends_on:
      - rabbitmq
